spring :
  data:
    mongodb:
      url: mongodb://localhost:27017/admin
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      format_sql: true
    database-platform: org.hibernate.dialect.MySQL5Dialect
    show-sql: false